# Import Library

In [11]:
!pip install google-play-scraper
# Mengimpor pustaka google_play_scraper untuk mengakses ulasan dan informasi aplikasi dari Google Play Store.
from google_play_scraper import app, reviews, Sort, reviews_all

#Mengimpor csv untuk menyimpan hasil scrapping ke dalam file csv
import csv
#Mengimpor pandas untuk membuat data frame
import pandas as pd

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.11/dist-packages (1.2.7)

# Scrapping

In [12]:
scrap_review, _ = reviews(
                'com.google.android.calendar',
                lang='id',
                country='id',
                sort=Sort.MOST_RELEVANT,
                count=10000
)

Saya menggunakan ulasan dari aplikasi **Google Calendar** dengan mengambil **10.000** ulasan pengguna yang dianggap paling relevan.

In [13]:
# Mengubah hasil scraping menjadi dataframe
df = pd.DataFrame(scrap_review)
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,4c1adc4e-6ca0-46e8-a2cc-862429cd4c07,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tampilan bulan dengan kalender alternatif dibu...,4,7,2025.11.0-737427633-release,2025-03-31 10:21:11,None,NaT,2025.11.0-737427633-release
1,1d2d2f05-6848-4ded-b825-982a1dbd0a27,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,tolong developer perbaiki tampilan menu bulan ...,2,9,2025.09.1-732918122-release,2025-03-26 01:23:24,None,NaT,2025.09.1-732918122-release
2,07eef886-1fce-4a83-b4fe-3a4e5b8d7dfb,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Suka banget app ini, praktis dan lengkap, hany...",5,101,2025.05.1-722559100-release,2025-02-21 16:09:33,None,NaT,2025.05.1-722559100-release
3,3c1a1d12-ffd0-440a-830f-21132056fef0,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Suka banget sama aplikasinya. Kalo mau buat ja...,5,301,2024.42.0-687921584-release,2024-11-03 02:11:08,None,NaT,2024.42.0-687921584-release
4,0f58951f-61c4-49e4-b553-61503a90a6a6,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,masa update terus sihh tiap seminggu sekali up...,1,9,2025.09.1-732918122-release,2025-03-21 12:57:15,None,NaT,2025.09.1-732918122-release

Membuat data frame baru yang akan digunakan untuk analisis agar lebih storage lebih efisien, fokus, dan juga praktis

In [14]:
# memilih baris yang akan digunakan untuk analisis
data_review = df[['content', 'score']]
data_review.head()

                                             content  score
0  tampilan bulan dengan kalender alternatif dibu...      4
1  tolong developer perbaiki tampilan menu bulan ...      2
2  Suka banget app ini, praktis dan lengkap, hany...      5
3  Suka banget sama aplikasinya. Kalo mau buat ja...      5
4  masa update terus sihh tiap seminggu sekali up...      1

# Save file to csv

In [15]:
data_review.to_csv('google_calendar_review.csv', index=False)

Mengkonversi data frame ke format csv.